[package]
name = "RVVP"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
vulkano = "0.35.2"
winit = "0.30.12"
image = "0.25.8"
ffmpeg-next = { version = "8.0.0", features = ["default", "static"] }
rodio = "0.21.1"

[profile.dev]
opt-level = 1